### ISSUE TITLE
Update mdbook with new manifest format

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#199]
- After https://github.com/FuelLabs/fuel-indexer/pull/178 lands we'll have a new format for manifest files
- The format seems to be changing from
```yaml
namespace: counter
graphql_schema: schema/counter.graphql
handlers:
  - event: an_event_name
    handler: count_handler
```

...to...

```yaml
namespace: test_namespace
graphql_schema: schema.graphql
module:
  wasm:
    simple_wasm.wasm
handlers:
  - event: an_event_name
    handler: function_one
```
- We should update the mdbook accordingly
