### ISSUE TITLE
Running indexer on beta-2 testnet

### ISSUE THREAD

**Issue by atulpatare** [FuelLabs/fuel-indexer#361]
The indexer fails to run when the host is pointed to the beta-2 testnet. Following is the config and error log.

- The `config.yaml` file
``` yaml

fuel_node:
  # tested with `http` and without `http` also `https`
  host: http://node-beta-2.fuel.network
  port: 80

```

- The error log
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(Socket)',
fuel-indexer-lib/src/config.rs:164:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

- Command used to run
```shell
cargo run -p fuel-indexer -- --config config.yaml

# also
./target/debug/fuel-indexer --config config.yaml
```

- If the config is using `host: <ip_address>`  it works fine as in with read `blocks` or will fail `fetching blocks` but not the above error.

I have also searched this issue and found #168 but that too doesn't work.
