### ISSUE TITLE
Add a `cargo-udeps` CI check to check for unused dependencies

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel-indexer#62]
Just a reminder to look into this! I tried adding this in #31 but it seems to pick up some false-positives due to not being able to reason about dependencies used within proc macros.

Perhaps instead we can just run it directly for a few specific big crates and avoid running it for those that use the proc macros producing false positives.

This is the job I was trying to add that could be a decent place to start from:

```yaml
  cargo-unused-deps-check:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          # `cargo-udeps` requires nightly to run
          toolchain: nightly
          default: true
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-udeps
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps
      - name: Check Unused Deps
        uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --locked --all-targets
```
