### ISSUE TITLE
Add a `cargo test --all-features` job to CI

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel-indexer#63]
Currently we test for the default feature set and `--no-default-features`, though we should also support `--all-features`:

```yaml
  cargo-test-workspace-all-features:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Cargo Test Workspace
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --workspace --all-features --all-targets
        env:
          RUSTFLAGS: '-D warnings'
```

Currently, attempting to run this results in some failure in the executor root tests. The following results are from a run when attempting to land the above job in #31 ([link to the failed action](https://github.com/FuelLabs/fuel-indexer/runs/6873176297?check_suite_focus=true)):

```
     Running unittests src/lib.rs (target/debug/deps/fuel_wasm_executor-32b9bea8c23858c8)
running 2 tests
test executor::tests::test_executor ... FAILED
test database::tests::test_schema_manager ... FAILED
failures:
---- executor::tests::test_executor stdout ----
thread 'executor::tests::test_executor' panicked at 'Expected missing handler error Err(
    ConnectionError(
        BadConnection(
            "connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n",
        ),
    ),
)', indexer/src/executor.rs:179:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- database::tests::test_schema_manager stdout ----
thread 'database::tests::test_schema_manager' panicked at 'Could not create SchemaManager: DatabaseInitError(Error(Some("connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n")))', indexer/src/database.rs:257:56
failures:
    database::tests::test_schema_manager
    executor::tests::test_executor
test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 30.00s
error: test failed, to rerun pass '-p fuel-wasm-executor --lib'
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

We should aim to land this in CI sooner rather than later in order to avoid falling further away from supporting the flag.
